ReverseProxy:
  Routes:
    identity_ui_route:
      ClusterId: "identity_server_cluster"
      Match:
        Path: "/auth/{**catch-all}"
    identity_api_route: 
      ClusterId: "identity_server_cluster"
      Match:
        Path: "/api/auth/{**catch-all}"
    identity_token_route:
      ClusterId: "identity_server_cluster"
      Match:
        Path: "/connect/{**catch-all}"
    # BỔ SUNG THÊM ROUTE NÀY
    identity_discovery_route:
      ClusterId: "identity_server_cluster"
      Match:
        Path: "/.well-known/{**catch-all}"

  Clusters:
    identity_server_cluster:
      Destinations:
        identity_node:
          Address: "https://localhost:7133"
      Transforms:
        - RequestHeader: X-Forwarded-For
          Append: "{RemoteIpAddress}"
        - RequestHeader: X-Forwarded-Proto
          Set: "https"
        - RequestHeader: X-Forwarded-Host
          Set: "{Host}"